INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Black Mountain Loop', 49.395863, -123.203891, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Black Mountain Loop: Length: 2.5 kilometres. Suggested time: just over 90 minutes. Elevation change: 100 metres. Situated astride Black Mountain Plateau, the trail winds through sub-alpine meadows, skirting the edges of several mountain lakes. Quoted length and time include the recommended side trips to enjoy the Yew Lake viewpoint and the Vancouver look-out.', 'Open', 'No Warnings', 1, 50);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Hollyburn Trail', 49.379274, -123.191640, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Hollyburn Peak Trail: Length: 1.3 kilometres. Length from Nordic Ski Area: 8 kilometres (return) Suggested time: 4 hours. Elevation change: 400 metres. From the Nordic Ski Area Parking lot, hike up the powerline road to the Baden-Powell trail. Follow the signs up the mountain to the Hollyburn Peak Trail. This trail leads to the top of Hollyburn Mountain and offers spectacular views of the surrounding area.', 'Closed', 'Bear Warning!', 1, 50);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Howe Sound Crest Trail', 49.395901, -123.203933, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Howe Sound Crest Trail: Length: 29 kilometres (one way).Trail begins in the Cypress Mountain Resort Alpine ski area and leads north along Mount Strachan’s western slope past the Lions and Deeks Lake before descending to Hwy 99 just south of Porteau Cove Provincial Park. Sections of the trail are extremely rugged and easy to lose in inclement weather. Only experienced and well-equipped backcountry travellers should attempt to hike this trail beyond the Bowen Lookout. Winter use of the trail is not recommended beyond Bowen Lookout.', 'Closed', 'Snake Warning!', 1, 100);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Cheakamus Lake Trailhead', 50.042258, -122.9891968, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Cheakamus Lake to Black Tusk Meadows via Helm Creek: Length, 14.5 km; suggested time, 6 to 7 hours one way; elevation change, 600 metres. Located 1.5 km along the Cheakamus Lake trail, the trail drops down to a bridge across the Cheakamus River. On the other side of the river the trail switchbacks upward, following Helm Creek past the Helm Creek campground, through the Cinder Flats, to the Upper Lakes and the meadows.', 'Open', 'No Warnings', 2, 100);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Diamond Head Trailhead', 49.750175, -123.053186, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Parking Lot to Elfin Lakes: Length, 11 km; suggested time, 3 to 5 hours one way; elevation change, 600 metres. The trail follows Paul Ridge and provides beautiful vistas. At Elfin Lakes, Columnar Peak, the Gargoyles, Opal Cone and Mamquam Icefield come into view.

Elfin Lakes to Little Diamond Head: Length, 7 km; suggested time, 2 to 3 hours one way; elevation change, 625 metres. This is a fairly arduous hike past the Gargoyles (strange visages sculptured by nature in lava) to 2,100 metre Little Diamond Head.

Elfin Lakes to the Opal Cone: Length, 6.5 km; suggested time, 2 to 3 hours one way; elevation change, 250 metres. Trail leads down to Ring Creek then climbs the Opal Cone, an extinct volcano with a crater. Garibaldi Neve and Mamquam Lake can be seen from the top. 

Elfin Lakes to Mamquam Lake: Length, 11 km; suggested time, 4 to 5 hrs one way; elevation change, 570 metres. A strenuous hike that follows the route to the Opal Cone and then continues eastward past the Rampart Ponds. The trail descends to the lake from here. Overnight camping is not permitted.', 'Open', 'No Warnings', 2,150);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Rubble Creek Trailhead', 49.750175, -123.053186,'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Cheakamus Lake to Black Tusk Meadows via Helm Creek: Length, 14.5 km; suggested time, 6 to 7 hours one way; elevation change, 600 metres. Located 1.5 km along the Cheakamus Lake trail, the trail drops down to a bridge across the Cheakamus River. On the other side of the river the trail switchbacks upward, following Helm Creek past the Helm Creek campground, through the Cinder Flats, to the Upper Lakes and the meadows.', 'Open', 'No Warnings', 2, 100);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Chief Peaks Trail', 49.678642, -123.154516,'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Stawamus Chief Provincial Park protects the 700-metre massive granite cliffs that stand at the southern entrance to Squamish on the scenic Sea to Sky Highway.
The park provides rock climbing opportunities of international significance. Hiking trails to The Chief’s three summits offer rewarding views of Howe Sound, Squamish town site and surrounding mountains. This park has opportunities for camping, hiking, rock climbing and scenic viewing atop the Chief.', 'Closed', 'Snake Warning!U+1F613	', 6,100);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Upper Mountain Trails', 49.367516, -122.94921, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Mount Seymour Provincial Park has 14 hiking trails of varying lengths and difficulty. Trail maps are available at the information board at the Old Buck parking lot near the park’s entrance, at the north end of parking lot 4 and at the Baden-Powell parking lot. For your own safety and the preservation of the park, obey posted signs and keep to designated trails. Shortcutting trails destroys plant life and soil structure. In addition, winter trails are created annually.', 'Open', 'No Warnings', 5, 100);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Berg Lake Trail', 53.1440, 119.1591, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'This trail takes hikers to some of the best scenery in the province. Beyond Kinney Lake, the trail enters the Valley of a Thousand Falls. Fed by the massive Mist, Berg and Robson glaciers, visitors often see huge sections of ice break off or “calve” into the blue/green, silt-laden waters of Berg Lake. Berg Lake campsite is 21 km from the trailhead parking lot. Use one of the campgrounds as a base and take in some day hiking or continue past Robson Pass campground for a challenging excursion.', 'Closed', 'Warnings', 4, 200);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('Alouette Lake', 49.3337,  122.4181, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Alouette Lake is a popular spot for swimming, windsurfing, water-skiing, canoeing, boating and fishing. The park also has three large campgrounds. Vegetation is typical of the coastal western Hemlock forest of B.C. and the mountainous backcountry is extremely rugged.', 'Open', 'No Warnings', 3, 200);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('East/West Canyon', 49.3337,  122.4181, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Alouette Lake is a popular spot for swimming, windsurfing, water-skiing, canoeing, boating and fishing. The park also has three large campgrounds. Vegetation is typical of the coastal western Hemlock forest of B.C. and the mountainous backcountry is extremely rugged.', 'Closed', 'Bear Warning!', 3, 100);

INSERT INTO trails (name, latitude, longitude, image, description,status, warning, park_id, max_capacity)
VALUES ('South Beach', 49.3337,  122.4181, 'https://lh3.googleusercontent.com/proxy/4IYcjfJoSXUE5e6d82I5euxlgku9v7r9vdnhyMjtVcoTg8vpfIoodcXlVJRyOYa641L4axcZ2114w3gsrGfvhoKDak_AE6lfoqtusIYdnPLVOaj_Sm8', 'Alouette Lake is a popular spot for swimming, windsurfing, water-skiing, canoeing, boating and fishing. The park also has three large campgrounds. Vegetation is typical of the coastal western Hemlock forest of B.C. and the mountainous backcountry is extremely rugged.', 'Open', 'No Warnings', 3, 200);